<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sign in</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 330px;
            padding: 15px;
            margin: auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }

        .sign-in {
            margin-top: 5px;
        }
    </style>
</head>

<body class="text-center">

    <main class="form-signin">
        <form method="post" action="/user/activate">
            <img class="mb-4" src="https://d1nggucqgkhstg.cloudfront.net/img/letscodelogo190.png" alt="" width="72" height="72">
            <h1 class="h3 mb-3 fw-normal">Please set your password</h1>
            <input type="hidden" name="token" value="<?= $token ?>" />
            <div class="form-floating">
                <input type="password" name="password" class="form-control" id="floatingInput" placeholder="Password">
                <label for="floatingInput">Password</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password_confirm" class="form-control" id="floatingPassword" placeholder="Password confirmation">
                <label for="floatingPassword">Confirm</label>
            </div>

            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Activate</button>
        </form>
        <a href="/login" class="w-100 sign-in btn btn-lg btn-secondary ">Sign in</a>
    </main>
</body>

</html>
